version: "3.8"

services:
  web:
    build: ./client
    ports:
      - "3000:3000"
  api:
    build: ./server
    ports:
      - "5000:3001"
    # environment:
      # DB_URL: "mongodb://mongo:27017"

#  if we have a database
#   mongodb:
#     image: mongo:4.0-xenial
#     ports:
#       - "27017:27017"
#     volumes:
#       - friendnet:/data/db

# volumes:
#   friendnet:
