version: "3.8"

services:
  client:
    build: ./client
    ports:
      - 5173:5173
  server:
    build: ./server
    ports:
      - 5000:3001
    # environment:
      # DB_URL: mongodb://db/friendnet

#  if we have a local database
#   mongodb:
#     image: mongo:4.0-xenial
#     ports:
#       - 27017:27017
#     volumes:
#       - friendnet:/data/db

# volumes:
#   friendnet:
