version: "3.8"

services:
  client:
    build: ./client
    ports:
      - 5173:5173
    # # Publishing changes with the container
    # volumes:
    #   - ./client:/app

    # to run tests automatically
  client-tests:
    image: friendnet_client
    # # Publishing changes with the container
    # volumes:
    #   - ./client:/app
    command: npm test

  server:
    build: ./server
    ports:
      - 3001:3001
    environment:
      MONGO_URI: mongodb://db/SocialMedia
      JWT_SECRET: MY_JWT_SECRET
      # DB_URL: mongodb://db/friendnet
    # volumes:
    #   - ./server:/app
    # command: ./docker-entrypoint.sh

  # local db
  db:
    image: mongo
    container_name: "my-mongo"
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME:
    #   MONGO_INITDB_ROOT_PASSWORD:
    volumes:
      - friendnet:/data/db
    ports:
      - 27017:27017
volumes:
  friendnet:
      

#  if we have a local database
#   mongodb:
#     image: mongo:4.0-xenial
#     ports:
#       - 27017:27017
#     volumes:
#       - friendnet:/data/db

# define valum before using it

